### ISSUE TITLE
Support for other keyboards

### ISSUE THREAD

**Issue by noseglasses** [keyboardio/Kaleidoscope-Hardware-Virtual#14]
When Kaleidoscope-Hardware-Virtual was written, the Model01 was "the" keyboard running Kaleidoscope (and it still is). That's probably the reason why the hardware that KHV represents is one with 64 keys, 4 matrix rows and 16 columns. 

For future use it would be desirable to generalize the virtual hardware in a way to allow for other keyboards to be simulated. 

The following macros, defined in hardware specification headers, can be useful to other software that is based on KHV, e.g. to determine what keyboard is simulated.
* HARDWARE_IMPLEMENTATION
* COLS
* ROWS

My current practical problem is that I would like to allow Kaleidoscope-Python to determine what keyboard is simulated, to generate a matching graphical representation ([see here for an example of the M01](https://community.keyboard.io/t/mapping-keycodes-back-to-verbose-keycode-descriptions/889/5?u=noseglasses)).

I thought about a way to enable KHV to read the actual hardware specification header of a keyboard, e.g. `Kaleidoscope-Hardware-Model01.h` and determine the necessary information like number of rows/cols. Unfortunately, it is not possible to just include a "real" hardware header in the compiled code as this would automatically cause the Arduino build system to build all code that is related with the real hardware. This leads to numerous build errors, as a lot of stuff related to the actual hardware cannot be build in the virtual context.

I am still not familiar with the Arduino build system, therefore I would appreciate if someone with more knowledge could provide information about whether there is some alternative way to determine the keyboard characteristics without including the device hardware header. 

Outside of the restricted world of Arduino's build system, it is very easy to determine the required information from an actual hardware header and then to supply this information via command line macro definitions. If there is no other solution, we could modify `Kaleidoscope-Hardware-Virtual.h` in a way that the above macros are only defined if they have not yet been defined before (at the compiler command line). The default values would of course remain those of the M01.

What do you think?

**Comment by cdisselkoen** [comment]
While I definitely agree with the desire to make KHV more hardware-agnostic, I'm not sure that a mechanistic/automated way to implement alternate "hardwares" in KHV is warranted, especially as it seems to be a nontrivial amount of effort.  A simpler solution could be just having a compile-time switch (based on an environment variable) that chooses the correct values of COLS, ROWS, etc for the targeted hardware, defaulting to the Model 01 values of course.  Implementing a new hardware in KHV would then require adding another case to this switch statement - certainly not a big ask compared to the amount of manual effort required elsewhere in Kaleidoscope to port to a new hardware. 

I could be wrong, and I'm willing to be convinced otherwise.

**Comment by obra** [comment]
In my ideal world, I think the way that we'd see a wider variety of
'alternate' hardware backends is for KHV to get broken out into an Arduino
core and one or more board implementations that uses that core. As far as I
can tell, Craig's work is, to date, the most comprehensive 'Arduino API
Simulator' implementation that compiles to local code. If if were lifted
out, we might be able to sucker additional volunteers into helping make it
more featureful and flexible, as there are lots of other possible use cases.

-jesse

**Comment by noseglasses** [comment]
> A simpler solution could be just having a compile-time switch (based on an environment variable) that chooses the correct values of COLS, ROWS, etc

Craig's suggestion would definitely be an improvement and easy to implement.

> In my ideal world, I think the way that we'd see a wider variety of 'alternate' hardware backends is for KHV to get broken out into an Arduino core and one or more board implementations that uses that core.

KHV has parts that deal with the x86 build and others, C++ code, that represent a Kaleidoscope hardware. Those two could be separated, right? The build system part would be moved to a new Arduino core and the rest would remain in KHV? 

This sounds like a good idea to me, but the OP was about how to pass appropriate values of `HARDWARE_IMPLEMENTATION`, `ROWS` and `COLS` through to the fimware C++ compile.

@obra: Could the latter be solved by the proposed refactoring?

**Comment by obra** [comment]
I've been starting to try to tease this apart. Right now, https://github.com/keyboardio/Kaleidoscope-Bundle-Keyboardio/tree/master/x86 is a version of the 'support' library from this plugin. I have several changes to the plugin to help get it closer to compiling. My goal is to split apart the generic parts that offer an Arduino core for native x86 builds, the parts that offer an x86 test keyboard implementation and the parts that offer a faux-Model-01 implementation.

**Comment by noseglasses** [comment]
Now as virtual builds are possible for (almost) all keyboards that are currently part of the core repo, this issue is obsolete. Closing.
