### ISSUE TITLE
Code for virtual hardware strangely spread

### ISSUE THREAD

**Issue by noseglasses** [keyboardio/Kaleidoscope-Hardware-Virtual#21]
The code for virtual firmware builds is strangely split up in two parts.

The code of the virtual core resides in `Kaleidoscope-Bundle-Keyboardio`. Other
stuff that replaces the hardware-specific parts of Kaleidoscope with virtual representations resides in 
`Kaleidoscope-Hardware-Virtual`. The one cannot build without the other.

For developers it's pretty inconvenient and confusing as it takes extra time to understand how everything works together. I know that this is mostly due to the constraints that Arduino imposes on the code structure. But maybe we can make this more transparent.

This used to be different in the original version of Kaleidoscope-Hardware-Virtual that was designed as a standalone plugin. Then symbolic links were used that pointed from the hardware directory to the plugin representation of the virtual core.

Symlinks are problematic in Windows as their creation required administrator privileges at least in older versions of Windows. That's why it's not a good idea to use them in a project that is meant to be portable.

Any ideas how to resolve this? Can it be solved at all?

**Comment by noseglasses** [comment]
IMHO, it would make sense to move the entire code of the virtual hardware to the virtual architecture dir of the bundle and let this be a submodule of its own. Then all the virtual code wouldn't be spread on multiple repos anymore.

Does that make sense?

**Comment by obra** [comment]
Yes. Your idea makes sense. The reason why it is currently split up is that I had started that process, but parts of the virtual build were broken enough that I couldn’t finish it

**Comment by noseglasses** [comment]
This repo has become obsolete as parts of it were merged to other places in the core firmware repo and the firmware bundle. Closing.
